name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write # Allows branch and content modifications
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ashesbloom
          outputs: dist/snake.svg?palette=github-dark

      - name: Create or update output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Generated snake.svg"
          git push origin +HEAD:refs/heads/output # Force push to create/update output branch
        env:
          GITHUB_TOKEN: ${{ secrets.README_SNAKE_COMITS }}
